FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y \
        iproute2 \
        iputils-ping \
        traceroute \
        dnsutils \
        iptables \
        netcat \
        curl \
        nmap \
        tcpdump \
        iperf \
        less \
        vim \
