name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up qemu-user-static for arm64 binary execution
      run: docker run --rm --privileged multiarch/qemu-user-static:5.2.0-2 --reset -p yes
    - name: Set up multi-arch supported Docker builder
      run: docker buildx create --use --name multi-arch
    - name: Build the Docker images
      run: make build
    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin
    - name: Push the Docker images
      run: make push
