name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image of cloud-image-utils
      run: docker build -f cloud-image-utils/Dockerfile -t cloud-image-utils cloud-image-utils

    - name: Build the Docker image of qemu-utils
      run: docker build -f qemu-utils/Dockerfile -t qemu-utils qemu-utils
